-- =====================================================
-- ÍNDICES E CONSTRAINTS PARA PERFORMANCE IOT
-- Challenge 2025 - 4º Sprint
-- =====================================================

-- Índices para Dispositivos IoT
CREATE INDEX IDX_DISPOSITIVO_TIPO ON T_MT_DISPOSITIVO_IOT (TP_DISPOSITIVO);
CREATE INDEX IDX_DISPOSITIVO_STATUS ON T_MT_DISPOSITIVO_IOT (ST_STATUS);
CREATE INDEX IDX_DISPOSITIVO_ZONA ON T_MT_DISPOSITIVO_IOT (CD_ZONA);
CREATE INDEX IDX_DISPOSITIVO_LOCALIZACAO ON T_MT_DISPOSITIVO_IOT (NR_LATITUDE, NR_LONGITUDE);

-- Índices para Sensor Dados
CREATE INDEX IDX_SENSOR_DISPOSITIVO ON T_MT_SENSOR_DADOS (ID_DISPOSITIVO);
CREATE INDEX IDX_SENSOR_TIPO ON T_MT_SENSOR_DADOS (TP_SENSOR);
CREATE INDEX IDX_SENSOR_DATA ON T_MT_SENSOR_DADOS (DT_LEITURA);
CREATE INDEX IDX_SENSOR_PROCESSADO ON T_MT_SENSOR_DADOS (ST_PROCESSADO);
CREATE INDEX IDX_SENSOR_DISPOSITIVO_DATA ON T_MT_SENSOR_DADOS (ID_DISPOSITIVO, DT_LEITURA);

-- Índices para Alertas
CREATE INDEX IDX_ALERTA_TIPO ON T_MT_ALERTA (TP_ALERTA);
CREATE INDEX IDX_ALERTA_SEVERIDADE ON T_MT_ALERTA (NV_SEVERIDADE);
CREATE INDEX IDX_ALERTA_ATIVO ON T_MT_ALERTA (ST_ATIVO);
CREATE INDEX IDX_ALERTA_DATA ON T_MT_ALERTA (DT_CRIACAO);
CREATE INDEX IDX_ALERTA_MOTO ON T_MT_ALERTA (CD_PLACA_MOTO);
CREATE INDEX IDX_ALERTA_DISPOSITIVO ON T_MT_ALERTA (ID_DISPOSITIVO);
CREATE INDEX IDX_ALERTA_ZONA ON T_MT_ALERTA (CD_ZONA);

-- Índices para Histórico de Uso
CREATE INDEX IDX_HISTORICO_PLACA ON T_MT_HISTORICO_USO (CD_PLACA);
CREATE INDEX IDX_HISTORICO_USUARIO ON T_MT_HISTORICO_USO (CD_CPF_USUARIO);
CREATE INDEX IDX_HISTORICO_INICIO ON T_MT_HISTORICO_USO (DT_INICIO_USO);
CREATE INDEX IDX_HISTORICO_STATUS ON T_MT_HISTORICO_USO (ST_USO);
CREATE INDEX IDX_HISTORICO_PLACA_DATA ON T_MT_HISTORICO_USO (CD_PLACA, DT_INICIO_USO);

-- Índices para Localização das Motos
CREATE INDEX IDX_LOC_MOTO_STATUS ON T_MT_LOCALIZACAO_MOTO (ST_STATUS_MOTO);
CREATE INDEX IDX_LOC_MOTO_ZONA ON T_MT_LOCALIZACAO_MOTO (CD_ZONA);
CREATE INDEX IDX_LOC_MOTO_SETOR ON T_MT_LOCALIZACAO_MOTO (DS_SETOR);
CREATE INDEX IDX_LOC_MOTO_BATERIA ON T_MT_LOCALIZACAO_MOTO (NR_BATERIA);
CREATE INDEX IDX_LOC_MOTO_ATUALIZACAO ON T_MT_LOCALIZACAO_MOTO (DT_ULTIMA_ATU);

-- Índices para Eventos IoT
CREATE INDEX IDX_EVENTO_ALERTA ON T_MT_EVENTO_IOT (ID_ALERTA);
CREATE INDEX IDX_EVENTO_DISPOSITIVO ON T_MT_EVENTO_IOT (ID_DISPOSITIVO);
CREATE INDEX IDX_EVENTO_DATA ON T_MT_EVENTO_IOT (DT_EVENTO);
CREATE INDEX IDX_EVENTO_PROCESSADO ON T_MT_EVENTO_IOT (ST_PROCESSADO);

-- Índices para Push Tokens
CREATE INDEX IDX_PUSH_USUARIO ON T_MT_PUSH_TOKEN (CD_CPF_USUARIO);
CREATE INDEX IDX_PUSH_FUNCIONARIO ON T_MT_PUSH_TOKEN (ID_FUNCIONARIO);
CREATE INDEX IDX_PUSH_ATIVO ON T_MT_PUSH_TOKEN (ST_ATIVO);
CREATE INDEX IDX_PUSH_PLATAFORMA ON T_MT_PUSH_TOKEN (DS_PLATAFORMA);

-- Índices para Auditoria
CREATE INDEX IDX_AUD_TABELA ON T_MT_AUDITORIA (NM_TABELA);
CREATE INDEX IDX_AUD_REGISTRO ON T_MT_AUDITORIA (ID_REGISTRO);
CREATE INDEX IDX_AUD_OPERACAO ON T_MT_AUDITORIA (TP_OPERACAO);
CREATE INDEX IDX_AUD_DATA ON T_MT_AUDITORIA (DT_OPERACAO);
CREATE INDEX IDX_AUD_USUARIO ON T_MT_AUDITORIA (CD_CPF_USUARIO);
CREATE INDEX IDX_AUD_FUNCIONARIO ON T_MT_AUDITORIA (ID_FUNCIONARIO);

-- Constraints de Check para validação de dados
ALTER TABLE T_MT_DISPOSITIVO_IOT ADD CONSTRAINT CK_DISPOSITIVO_STATUS 
    CHECK (ST_STATUS IN ('ONLINE', 'OFFLINE', 'MANUTENCAO', 'ERRO'));

ALTER TABLE T_MT_DISPOSITIVO_IOT ADD CONSTRAINT CK_DISPOSITIVO_TIPO 
    CHECK (TP_DISPOSITIVO IN ('sensor_movimento', 'camera', 'atuador_trava', 'atuador_alarme', 'sensor_temperatura', 'sensor_bateria'));

ALTER TABLE T_MT_ALERTA ADD CONSTRAINT CK_ALERTA_SEVERIDADE 
    CHECK (NV_SEVERIDADE IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

ALTER TABLE T_MT_ALERTA ADD CONSTRAINT CK_ALERTA_TIPO 
    CHECK (TP_ALERTA IN ('iot', 'sistema', 'manutencao', 'seguranca', 'bateria', 'movimento'));

ALTER TABLE T_MT_ALERTA ADD CONSTRAINT CK_ALERTA_ATIVO 
    CHECK (ST_ATIVO IN ('S', 'N'));

ALTER TABLE T_MT_HISTORICO_USO ADD CONSTRAINT CK_HISTORICO_STATUS 
    CHECK (ST_USO IN ('EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO'));

ALTER TABLE T_MT_HISTORICO_USO ADD CONSTRAINT CK_HISTORICO_DISTANCIA 
    CHECK (NR_DISTANCIA_KM >= 0);

ALTER TABLE T_MT_HISTORICO_USO ADD CONSTRAINT CK_HISTORICO_TEMPO 
    CHECK (NR_TEMPO_USO_MIN >= 0);

ALTER TABLE T_MT_LOCALIZACAO_MOTO ADD CONSTRAINT CK_LOC_STATUS 
    CHECK (ST_STATUS_MOTO IN ('DISPONIVEL', 'EM_USO', 'MANUTENCAO', 'RESERVADA', 'INATIVA'));

ALTER TABLE T_MT_LOCALIZACAO_MOTO ADD CONSTRAINT CK_LOC_BATERIA 
    CHECK (NR_BATERIA BETWEEN 0 AND 100);

ALTER TABLE T_MT_SENSOR_DADOS ADD CONSTRAINT CK_SENSOR_PROCESSADO 
    CHECK (ST_PROCESSADO IN ('S', 'N'));

ALTER TABLE T_MT_EVENTO_IOT ADD CONSTRAINT CK_EVENTO_PROCESSADO 
    CHECK (ST_PROCESSADO IN ('S', 'N'));

ALTER TABLE T_MT_PUSH_TOKEN ADD CONSTRAINT CK_PUSH_ATIVO 
    CHECK (ST_ATIVO IN ('S', 'N'));

ALTER TABLE T_MT_PUSH_TOKEN ADD CONSTRAINT CK_PUSH_PLATAFORMA 
    CHECK (DS_PLATAFORMA IN ('ANDROID', 'IOS', 'WEB'));

ALTER TABLE T_MT_AUDITORIA ADD CONSTRAINT CK_AUD_OPERACAO 
    CHECK (TP_OPERACAO IN ('INSERT', 'UPDATE', 'DELETE'));

-- Constraints de validação de coordenadas
ALTER TABLE T_MT_DISPOSITIVO_IOT ADD CONSTRAINT CK_DISPOSITIVO_LATITUDE 
    CHECK (NR_LATITUDE BETWEEN -90 AND 90);

ALTER TABLE T_MT_DISPOSITIVO_IOT ADD CONSTRAINT CK_DISPOSITIVO_LONGITUDE 
    CHECK (NR_LONGITUDE BETWEEN -180 AND 180);

-- Triggers para atualização automática de timestamps
CREATE OR REPLACE TRIGGER TRG_DISPOSITIVO_IOT_UPD
    BEFORE UPDATE ON T_MT_DISPOSITIVO_IOT
    FOR EACH ROW
BEGIN
    :NEW.DT_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOCALIZACAO_MOTO_UPD
    BEFORE UPDATE ON T_MT_LOCALIZACAO_MOTO
    FOR EACH ROW
BEGIN
    :NEW.DT_ULTIMA_ATU := CURRENT_TIMESTAMP;
END;
/

-- Comentários nos índices
COMMENT ON INDEX IDX_SENSOR_DISPOSITIVO_DATA IS 'Índice composto para consultas por dispositivo e período';
COMMENT ON INDEX IDX_HISTORICO_PLACA_DATA IS 'Índice composto para histórico por moto e data';
COMMENT ON INDEX IDX_ALERTA_ATIVO IS 'Índice para consultas de alertas ativos';
