-- V1: Criação das tabelas principais
-- Tabela de Pátios
CREATE TABLE ST_PATIO (
    ID_PATIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255),
    COMPLEMENTO VARCHAR(100),
    AREA_M2 DECIMAL(10,2),
    ID_LOCALIDADE BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela de Motos
CREATE TABLE ST_MOTO (
    ID_MOTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(8) NOT NULL UNIQUE,
    STATUS VARCHAR(20) NOT NULL,
    ID_PATIO BIGINT NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MOTO_PATIO FOREIGN KEY (ID_PATIO) REFERENCES ST_PATIO(ID_PATIO)
);

-- Índices para performance
CREATE INDEX IDX_MOTO_PLACA ON ST_MOTO(PLACA);
CREATE INDEX IDX_MOTO_STATUS ON ST_MOTO(STATUS);
CREATE INDEX IDX_MOTO_PATIO ON ST_MOTO(ID_PATIO);
CREATE INDEX IDX_PATIO_NOME ON ST_PATIO(NOME);
