-- V2: Criação das tabelas de segurança e usuários
-- Tabela de Perfis/Roles
CREATE TABLE ST_ROLE (
    ID_ROLE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Usuários
CREATE TABLE ST_USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NOME_COMPLETO VARCHAR(150) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela de relacionamento Usuário-Role (Many-to-Many)
CREATE TABLE ST_USUARIO_ROLE (
    ID_USUARIO BIGINT NOT NULL,
    ID_ROLE BIGINT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_ROLE),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (ID_USUARIO) REFERENCES ST_USUARIO(ID_USUARIO),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ST_ROLE(ID_ROLE)
);

-- Índices para performance
CREATE INDEX IDX_USUARIO_USERNAME ON ST_USUARIO(USERNAME);
CREATE INDEX IDX_USUARIO_EMAIL ON ST_USUARIO(EMAIL);
CREATE INDEX IDX_USUARIO_ATIVO ON ST_USUARIO(ATIVO);
